name: Deploy

on: 
  push:
    branches: 
      - master
      - dev
    paths:
      - '.github/workflows/**'
      - 'docs/**'
      - 'package/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          publish_dir: docs/.vitepress/dist